#!/bin/sh

make $1 $2 package/dr_manager/clean
rm -rf ./staging_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/dr_manager
rm -rf ./staging_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/mb_tcp_test_client
rm -rf ./staging_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/gpio_key_monitor
make $1 $2 package/dr_manager/compile
